apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-app
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        url: https://kubernetes.default.svc
      - namespace: qa
        url: https://kubernetes.default.svc
      - namespace: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-poc-app'
    spec:
      project: kubecon-demo
      source:
        path: deploy
        repoURL: https://github.com/singhrohit444/argocd-app-of-apps-demo.git
        targetRevision: HEAD
      destination:
        server: '{{"{{"}}url{{"}}"}}'
        namespace: '{{"{{"}}namespace{{"}}"}}'
